# Generated by Django 2.0.5 on 2018-07-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual', models.CharField(max_length=200)),
                ('initial_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutuals', to='portfolio.Customer')),
            ],
        ),
    ]
